#!/bin/bash
# Call purge builds to make sure we have at least 10G free
set -e
TOOLS=$($RUNNER_CONFIG_CMD -g hg.tools_path)
SLAVEDIR=$($RUNNER_CONFIG_CMD -g buildbot.slave_dir)
cd $SLAVEDIR
python $TOOLS/buildfarm/maintenance/purge_builds.py 10 $SLAVEDIR
