#!/bin/bash
# Update any shared repos we have
if [ -z "$HG_SHARE_BASE_DIR" ]; then
    echo "HG_SHARE_BASE_DIR not set; exiting"
    exit
fi

if [ "$USER" != "cltbld" ]; then
        sudo -E -u cltbld $0 $*
        exit $?
fi

echo "Looking for hg repos in $HG_SHARE_BASE_DIR"
find $HG_SHARE_BASE_DIR -type d -name .hg -prune -printf '%h\0' | xargs -0 -P4 -t -n 1 hg pull -R
